### ISSUE TITLE
Scheduler: Trigger weekday not working if phone language is not english

### ISSUE THREAD

**Issue by NaxoLuc** [awareframework/aware-light-client#2]
In Scheduler.java the `now.getDisplayName(Calendar.DAY_OF_WEEK, Calendar.LONG, Locale.getDefault())` returns locale specific name e.g Montag for Monday in german. 

`AWARE::Scheduler com.aware.phone D Weekday MONDAY vs now MONTAG in trigger weekdays: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"]`

Workaround: modify the weekday array in studyConfig.json to the language you expect

A fix would be to change
`now.getDisplayName(Calendar.DAY_OF_WEEK, Calendar.LONG, Locale.getDefault())`
to
`now.getDisplayName(Calendar.DAY_OF_WEEK, Calendar.LONG, Locale.ENGLISH)`

**Comment by tinazhang128** [comment]
Thank you very much. This is super helpful.
