### ISSUE TITLE
Screen status sensor collect problematic status change patterns.

### ISSUE THREAD

**Issue by lfang1** [awareframework/aware-light-client#35]
The screen status change should follow specific orders:
1. on to off (1 to 0)
2. off to on (0 to 1)
3. on to unlocked (1 to 3)
4. off to locked (0 to 2)
5. unlocked to off (3 to 0)
However, in some dataset, two adjacent rows have the same screen status, e.g., off to off.
In addition, two adjacent rows have problematic status change pattern. e.g., off to unlocked.

**Comment by tinazhang128** [comment]
From our investigation, the 2 adjacent rows can be flipped order when the data is synced to remote db
